***Importing the Libraries:***
>*Here we'll be importing all the essential libraries needed for logistic regression.*

In [28]:
#Importing the required libraries for Logistic Regression
from sklearn.datasets import make_classification
from sklearn.preprocessing import LabelEncoder
from matplotlib import pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
import pandas as pd
import numpy as np
from sklearn.compose import ColumnTransformer
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
import pickle

***Importing the processed dataset:***

>*We're going to import the dataset that we've preprocessed in the previous step and now we're going to import it and assgin the features to X and Y.*



In [4]:
#Importing the processed data set
dataset = pd.read_csv(r'C:\Users\tanus\OneDrive\Desktop\Internship Assests\pat_data_clean.csv')
dataset.head()
dataset = dataset.drop(['Unnamed: 0'], axis='columns')

x = dataset.iloc[:, [1,2,-1,-2]].values
y = dataset.iloc[:, -3].values

#using label encoder to change "yes/no" to "1/0"
le = LabelEncoder()
y = le.fit_transform(y)

print("Features of X are:")
print(x)

print("Features of Y are:")
print(y)




Features of X are:
[[ 19   7   1   0]
 [ 24  59   0   1]
 [  4  43   0   1]
 ...
 [ 48  22   0   1]
 [  5 104   1   0]
 [  0  96   1   0]]
Features of Y are:
[0 0 0 ... 1 0 0]


In [5]:
#splitting Train, Test Data sets
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

***KNN Model***

In [6]:
#K Nearest Neighbor
knn = KNeighborsClassifier(n_neighbors=2)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)

score = metrics.accuracy_score(y_test, y_pred)
print("Accuracy of KNN Model:", score)

Accuracy of KNN Model: 0.8197708292872402


>***Accuracy of Linear Regression Model ~ 82%***

***Linear Regression Model***

In [7]:
#Linear Regression
lr = LogisticRegression()
lr.fit(X_train, y_train)

y_pred = lr.predict(X_test)

score = metrics.accuracy_score(y_test, y_pred)
print("Accuracy of Linear Regression Model: ", score)

Accuracy of Linear Regression Model:  0.8774241877757123


In [26]:
import numpy as np
input_data = (16,50,1,0)

# changing the input_data to numpy array
input_data_as_numpy_array = np.asarray(input_data)

# reshape the array as we are predicting for one instance
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

prediction = lr.predict(input_data_reshaped)
print(prediction)

if (prediction[0] == 0):
  print('patient is not adhered')
else:
  print('patient Adhered')

[0]
not adhered


In [29]:
filename = 'linear_regression.sav'
pickle.dump(lr, open(filename, 'wb'))

filename = 'KNN.sav'
pickle.dump(knn, open(filename, 'wb'))


>***Accuracy of Linear Regression Model ~ 88%***